/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Code.app;


import kaptainwutax.biomeutils.source.OverworldBiomeSource;
import kaptainwutax.featureutils.structure.Stronghold;
import kaptainwutax.featureutils.structure.Village;
import kaptainwutax.seedutils.mc.ChunkRand;
import kaptainwutax.seedutils.mc.MCVersion;
import kaptainwutax.featureutils.structure.SwampHut;
import kaptainwutax.seedutils.mc.pos.CPos;

import java.util.ArrayList;

public class Main {


    public static void main(String[] args) {
        SwampHut SwampHut = new SwampHut(MCVersion.v1_16_2);
        Village Village = new Village(MCVersion.v1_16_2);
        Stronghold Stronghold = new Stronghold(MCVersion.v1_16_2);
        ChunkRand myChunkRand = new ChunkRand();
        System.out.println("test");
        int regionX;
        int regionY;
        for (long structureSeed = 0; structureSeed < 1L << 48; structureSeed++) {
            CPos vil1 = Village.getInRegion(structureSeed, regionX = 0, regionY = 0, myChunkRand);
            CPos hut2 = SwampHut.getInRegion(structureSeed, regionX = 0, regionY = 1, myChunkRand);
            CPos hut3 = SwampHut.getInRegion(structureSeed, regionX = 1, regionY = 0, myChunkRand);
            CPos hut4 = SwampHut.getInRegion(structureSeed, regionX = 0, regionY = 1, myChunkRand);
            if (Math.abs(vil1.getX() - hut2.getX()) < 8) {
                System.out.println(vil1.toString());
                System.out.println(hut2.toString());


            }


        }
        ArrayList<Long> structureSeed = new ArrayList<>();
        OverworldBiomeSource OverworldBiomeSource=new OverworldBiomeSource(MCVersion.v1_16_2);
        for (Long structure : structureSeed) {
            CPos hut1 = SwampHut.getInRegion(structure, regionX = 0, regionY = 0, myChunkRand);
            for (int biomes = 0; biomes < 1 << 16; biomes++) {
             if (!SwampHut.canSpawn(hut1.getX().hut1.getY()).);
            }




        }


    }

}

